### ISSUE TITLE
update HDD and CDD

### ISSUE THREAD

**Issue by robinhasse** [pik-piam/mredgebuildings#7]
The calculation of HDD and CDD has been done once in `/home/buechner/ISIMIP/data.pp/franziska/HDD_CDD` and is since read from the rd3mod source folder in `mredgebuildings::readHDDCDD`. The calculation of HDD and CDD should be integrated into `mredgebuildings` to make it more dynamic and transparent. We will already make use of more recent climate scenarios from ISIMIP and also want to consider more RCP scenarios. We are especially missing RCP 1.9 which is available in the new ISIMIP data. @robinhasse started working on that [in mrremind](https://github.com/robinhasse/mrremind/blob/cddhdd/R/calcHDDCDD.R) before but this work is unfinished and the existing code could be improved. 

# Data

The ISIMIP data is a mess, I'm sorry.

## daily average surface temperature `tas`

`/p/projects/isimip/isimip/ISIMIP3b/InputData/climate/atmosphere/bias-adjusted/global/daily`
`/p/projects/isimip/isimip/ISIMIP3b/SecondaryInputData/climate/atmosphere/bias-adjusted/global/daily`

- GFDL-ESM4: ssp245
- UKESM1-0-LL: ssp119, ssp245
- MPI-ESM1-2-HR: ssp245
- IPSL-CM6A-LR: ssp119, ssp245, ssp460
- MRI-ESM2-0: ssp119, ssp245, ssp460

## population
`/p/projects/isimip/isimip/ISIMIP2b/SecondaryInputData/population`

## country mask
I'm not hundred percent sure about this.
`/p/projects/isimip/isimip/output_analysis/masks/Country/CountryMask.NtoS.nc`

# TODO

- [x] create `mredgebuildings::calcHDDCDD` with temporal integrated file reading
- [x] clarify with @tscheypidi, if it is still planned (or already possible) to pass `raster` objects in read and convert functions ([we need it](https://mattermost.pik-potsdam.de/rd3/pl/kjior9syjfbmpjdi78cyfhb18w))
- [x] extend `mrcommons::readISIMIP` to read daily average temperature, population and country mask and return them as `raster` objects
- [x] extend `mrcommons::convertISIMIP` to convert new data
- [x] remove file reading from `mredgebuildings::calcHDDCDD`

**Comment by robinhasse** [comment]
Fixed by #25
